name: Java CI Pipeline

on:
  push:
    branches: [ "springboot-bot", "dev" ]
  pull_request:
    branches: [ "springboot-bot", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Java setup (for backend)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # Node.js setup
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
          cache: 'npm'
          cache-dependency-path: 'MtdrSpring/backend/src/main/frontend/package-lock.json'  

      # Prettier check
      - name: Check frontend formatting with Prettier
        working-directory: MtdrSpring/backend/src/main/frontend  
        run: |
          npm ci
          npm run format-check