name: Java CI Pipeline

on:
  push:
    branches: [ "springboot-bot", "dev" ]
  pull_request:
    branches: [ "springboot-bot", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # BACKEND

      # Java setup (for backend)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # Spring javaFormat check
      - name: Check backend formatting with Spring JavaFormat
        working-directory: MtdrSpring/backend
        run: mvn spring-javaformat:apply

      # Run backend tests
      - name: Install backend dependencies
        working-directory: MtdrSpring/backend
        run: mvn clean test

      # FRONTEND

      # Node.js setup
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
          cache: 'npm'
          cache-dependency-path: 'MtdrSpring/backend/src/main/frontend/package-lock.json'  
      
      # Dependency Installation
      - name: Install frontend dependencies
        working-directory: MtdrSpring/backend/src/main/frontend
        run: npm ci

      # Prettier check
      - name: Check frontend formatting with Prettier
        working-directory: MtdrSpring/backend/src/main/frontend  
        run: npm run format-check

      # Run frontend tests
      - name: Run frontend tests
        working-directory: MtdrSpring/backend/src/main/frontend  
        run: CI=true npm test -- --passWithNoTests